import 'dart:io';

import 'package:test/test.dart';

import 'package:mockbeam_record/src/route_serializer.dart';
import 'package:mockbeam_record/src/route_store.dart';

void main() {
  final serializer = RouteSerializer();
  final target = Uri.parse('https://api.example.com');
  final fixedTime = DateTime.utc(2026, 5, 8, 14, 32, 0);

  // Helpers -------------------------------------------------------------------

  CapturedRoute get(String path, Object? data, {int status = 200}) =>
      CapturedRoute(method: 'GET', path: path, statusCode: status, data: data);

  // ---------------------------------------------------------------------------

  group('RouteSerializer.toYaml', () {
    test('includes the header comment with target and timestamp', () {
      final yaml = serializer.toYaml([], target: target, recordedAt: fixedTime);
      expect(yaml, contains('# Generated by MockBeam Record v1.0.0'));
      expect(yaml, contains('# Target: https://api.example.com'));
      expect(yaml, contains('# Recorded: 2026-05-08T14:32:00.000Z'));
    });

    test('writes [] for an empty route list', () {
      final yaml = serializer.toYaml([], target: target, recordedAt: fixedTime);
      expect(yaml, contains('[]'));
    });

    test('serialises path, method, statusCode, and data fields', () {
      final yaml = serializer.toYaml(
        [get('/users/1', {'id': 1, 'name': 'Alice'})],
        target: target,
        recordedAt: fixedTime,
      );
      expect(yaml, contains('path:'));
      expect(yaml, contains('/users/1'));
      expect(yaml, contains('method:'));
      expect(yaml, contains('GET'));
      expect(yaml, contains('statusCode: 200'));
      expect(yaml, contains('id: 1'));
      expect(yaml, contains('name:'));
      expect(yaml, contains('Alice'));
    });

    test('serialises nested maps', () {
      final yaml = serializer.toYaml(
        [get('/users/1', {'address': {'city': 'NYC'}})],
        target: target,
        recordedAt: fixedTime,
      );
      expect(yaml, contains('city:'));
      expect(yaml, contains('NYC'));
    });

    test('serialises array data', () {
      final yaml = serializer.toYaml(
        [get('/posts', [{'id': 1}, {'id': 2}])],
        target: target,
        recordedAt: fixedTime,
      );
      expect(yaml, contains('data:'));
      expect(yaml, contains('id: 1'));
      expect(yaml, contains('id: 2'));
    });
  });

  // ---------------------------------------------------------------------------

  group('RouteSerializer.toJson', () {
    test('outputs a JSON array', () {
      final json = serializer.toJson([get('/a', {'x': 1})]);
      expect(json.trimLeft(), startsWith('['));
      expect(json.trimRight(), endsWith(']'));
    });

    test('outputs [] for an empty list', () {
      expect(serializer.toJson([]), '[]');
    });

    test('includes all required fields', () {
      final json = serializer.toJson([get('/users/1', {'id': 1})]);
      expect(json, contains('"path"'));
      expect(json, contains('"method"'));
      expect(json, contains('"statusCode"'));
      expect(json, contains('"data"'));
    });
  });

  // ---------------------------------------------------------------------------

  group('RouteSerializer.merge', () {
    test('new route takes precedence over existing for the same key', () {
      final existing = [get('/a', 'old')];
      final fresh = [get('/a', 'new')];
      final merged = serializer.merge(fresh, existing);
      expect(merged.length, 1);
      expect(merged.first.data, 'new');
    });

    test('existing routes absent from new session are preserved', () {
      final existing = [get('/a', null)];
      final fresh = [get('/b', null)];
      final merged = serializer.merge(fresh, existing);
      expect(merged.length, 2);
      expect(merged.map((r) => r.path), containsAll(['/a', '/b']));
    });

    test('empty new routes returns all existing routes', () {
      final existing = [get('/a', null), get('/b', null)];
      final merged = serializer.merge([], existing);
      expect(merged.length, 2);
    });

    test('empty existing returns all new routes', () {
      final fresh = [get('/a', null)];
      expect(serializer.merge(fresh, []).length, 1);
    });
  });

  // ---------------------------------------------------------------------------

  group('RouteSerializer.loadExisting', () {
    test('returns empty list for a missing file', () async {
      final result = await serializer.loadExisting(
        '/tmp/mockbeam_nonexistent_${DateTime.now().millisecondsSinceEpoch}.yaml',
      );
      expect(result, isEmpty);
    });

    test('parses a valid YAML file into CapturedRoutes', () async {
      final tmp = await _writeTmp('''
- path: /users/1
  method: GET
  statusCode: 200
  data:
    id: 1
    name: Alice
''');
      addTearDown(() => tmp.deleteSync());

      final routes = await serializer.loadExisting(tmp.path);
      expect(routes.length, 1);
      expect(routes.first.path, '/users/1');
      expect(routes.first.method, 'GET');
      expect(routes.first.statusCode, 200);
      expect((routes.first.data as Map)['name'], 'Alice');
    });

    test('returns empty list when the file is not a YAML list', () async {
      final tmp = await _writeTmp('key: value\n');
      addTearDown(() => tmp.deleteSync());
      expect(await serializer.loadExisting(tmp.path), isEmpty);
    });
  });

  // ---------------------------------------------------------------------------

  group('RouteSerializer.writeTo (atomic)', () {
    test('creates parent directories and writes the file', () async {
      final dir = '/tmp/mockbeam_test_${DateTime.now().millisecondsSinceEpoch}';
      final path = '$dir/sub/out.yaml';
      addTearDown(() => Directory(dir).deleteSync(recursive: true));

      await serializer.writeTo(path, 'hello');
      expect(await File(path).readAsString(), 'hello');
    });

    test('no .tmp file remains after a successful write', () async {
      final path = '/tmp/mockbeam_atomic_${DateTime.now().millisecondsSinceEpoch}.yaml';
      addTearDown(() => File(path).deleteSync());

      await serializer.writeTo(path, 'content');
      expect(File('$path.tmp').existsSync(), isFalse);
    });
  });
}

Future<File> _writeTmp(String content) async {
  final f = File('/tmp/mockbeam_test_${DateTime.now().millisecondsSinceEpoch}.yaml');
  await f.writeAsString(content);
  return f;
}
