import 'dart:convert';
import 'dart:io';

import 'package:yaml/yaml.dart';
import 'package:yaml_writer/yaml_writer.dart';

import 'route_store.dart';

/// Converts [RouteStore] contents to `dio_mock_interceptor`-compatible YAML
/// or JSON, merges with existing files for `--append`, and writes atomically.
class RouteSerializer {
  /// Serializes [routes] to a YAML string with a header comment.
  ///
  /// The header records [target] and [recordedAt] (defaults to now). The
  /// body is a YAML list directly usable with `dio_mock_interceptor`.
  String toYaml(
    List<CapturedRoute> routes, {
    required Uri target,
    DateTime? recordedAt,
  }) {
    final ts = (recordedAt ?? DateTime.now().toUtc()).toIso8601String();

    final buf = StringBuffer()
      ..writeln('# Generated by MockBeam Record v1.0.0')
      ..writeln('# Target: $target')
      ..writeln('# Recorded: $ts')
      ..writeln();

    if (routes.isEmpty) {
      buf.writeln('[]');
      return buf.toString();
    }

    buf.write(YamlWriter().write(_routesToMaps(routes)));
    return buf.toString();
  }

  /// Serializes [routes] to a pretty-printed JSON string.
  ///
  /// The output is a JSON array compatible with `dio_mock_interceptor`'s
  /// JSON format option.
  String toJson(List<CapturedRoute> routes) =>
      const JsonEncoder.withIndent('  ').convert(_routesToMaps(routes));

  /// Loads routes from an existing YAML file at [path].
  ///
  /// Returns an empty list when the file does not exist, is empty, or cannot
  /// be parsed. Never throws — a corrupt existing file is treated as missing.
  Future<List<CapturedRoute>> loadExisting(String path) async {
    final file = File(path);
    if (!await file.exists()) return [];
    try {
      final raw = loadYaml(await file.readAsString());
      if (raw is! YamlList) return [];
      return [
        for (final item in raw)
          if (item is YamlMap)
            CapturedRoute(
              method: item['method'] as String,
              path: item['path'] as String,
              statusCode: item['statusCode'] as int,
              data: _fromYaml(item['data']),
            ),
      ];
    } catch (_) {
      return [];
    }
  }

  /// Merges [newRoutes] over [existing], returning a combined list.
  ///
  /// New routes take precedence: if both lists contain the same `method:path`
  /// key the newly recorded version wins (it is fresher). Existing routes
  /// whose keys are absent from [newRoutes] are preserved unchanged.
  List<CapturedRoute> merge(
    List<CapturedRoute> newRoutes,
    List<CapturedRoute> existing,
  ) {
    final result = <String, CapturedRoute>{};
    for (final r in existing) {
      result['${r.method}:${r.path}'] = r;
    }
    for (final r in newRoutes) {
      result['${r.method}:${r.path}'] = r;
    }
    return result.values.toList();
  }

  /// Writes [content] to [path] atomically via a `.tmp` rename.
  ///
  /// Creates parent directories when they do not exist. The final rename is
  /// an OS-level atomic operation so a crash cannot leave a partial file.
  Future<void> writeTo(String path, String content) async {
    final file = File(path);
    await file.parent.create(recursive: true);
    final tmp = File('$path.tmp');
    await tmp.writeAsString(content, flush: true);
    await tmp.rename(path);
  }

  // ---------------------------------------------------------------------------

  List<Map<String, Object?>> _routesToMaps(List<CapturedRoute> routes) => [
        for (final r in routes)
          <String, Object?>{
            'path': r.path,
            'method': r.method,
            'statusCode': r.statusCode,
            'data': r.data,
          },
      ];

  /// Recursively converts [YamlMap]/[YamlList] to plain Dart [Map]/[List].
  Object? _fromYaml(dynamic value) {
    if (value is YamlMap) {
      return {
        for (final e in value.entries) e.key.toString(): _fromYaml(e.value),
      };
    }
    if (value is YamlList) return [for (final v in value) _fromYaml(v)];
    return value;
  }
}
